# -*- coding: utf-8 -*-
"""PruebasCorn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AkyMrsJvzf3NRVu2w0DeSh5_7jMJ3wll
"""

import os

# 1. Definir la ruta de tu archivo zip
# (¡Asegúrate de cambiar "dataset_maiz.zip" por el nombre real de tu archivo!)
ruta_zip_local = '/content/Corn_classification-v3.zip'

# Ruta donde se va a descomprimir (la que usan los siguientes bloques)
ruta_destino = '/content/dataset'

# 2. Crear la carpeta de destino si no existe
os.makedirs(ruta_destino, exist_ok=True)

# 3. Descomprimir silenciosamente (-q) en la carpeta destino
print(f"Descomprimiendo {ruta_zip_local}...")
!unzip -q "{ruta_zip_local}" -d "{ruta_destino}"

print("¡Extracción completada! Ya puedes continuar con el Bloque 1.")

import tensorflow as tf
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D, Dropout
from tensorflow.keras.models import Model
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint, ReduceLROnPlateau
from sklearn.utils.class_weight import compute_class_weight
import numpy as np
import os

# --- CONFIGURACIÓN GLOBAL ---
IMG_SIZE = (224, 224)
BATCH_SIZE = 64
NUM_CLASSES = 3
BASE_DIR = '/content/dataset' # IMPORTANTE: Cambia esto por la ruta donde extraigas tus imágenes

from tensorflow.keras.models import load_model
import os

# --- DEFINIR LA RUTA DEL MODELO ---
# Guardamos la ruta exacta en una variable para cargar el modelo directamente
ruta_modelo_guardado = '/content/mejor_modelo_maiz_V3_38.keras'

# --- BLOQUE 6: EVALUACIÓN FINAL (EL EXAMEN DE GRADO) ---
print("Cargando el dataset de prueba (test)...")

# Asumiendo que dentro de tu zip hay una carpeta llamada 'test'
test_dataset = tf.keras.utils.image_dataset_from_directory(
    os.path.join(BASE_DIR, 'test'),
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    label_mode='categorical',
    shuffle=False # Lo ponemos en False para mantener el orden original
)

# 1. Cargamos el modelo que se guardó en tu Drive usando la nueva variable
print(f"\nCargando el mejor modelo desde: {ruta_modelo_guardado}")
modelo_final = load_model(ruta_modelo_guardado)

# 2. Le pasamos el dataset de test para que lo evalúe
print("Evaluando el modelo con las imágenes de test que NUNCA ha visto...")
loss, accuracy = modelo_final.evaluate(test_dataset)

# 3. Mostramos los resultados reales
print("\n=== RESULTADOS DEL EXAMEN FINAL ===")
print(f"  - Precisión Real (Accuracy): {accuracy * 100:.2f}%")
print(f"  - Pérdida (Loss): {loss:.4f}")
print("===================================")

import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing import image
import matplotlib.pyplot as plt

# --- 1. CONFIGURA TU IMAGEN Y TUS CLASES ---

# Pon aquí la ruta de la imagen que quieres analizar.
# (Puedes subir una foto al panel de Colab y copiar su ruta)

#Prueba con test

#ruta_imagen_prueba = '/content/dataset/test/Blight/Corn_Blight-170-_JPG.rf.baa68ea02a74707a17edebd4af214407.jpg'

#No funciona XD

#ruta_imagen_prueba = '/content/Health_prueba.jpg'

#ruta_imagen_prueba = '/content/Common_rust_prueba.jpg'

#ruta_imagen_prueba = '/content/Common_rust_3_prueba.jpg'

#Funciona

#ruta_imagen_prueba = '/content/Blight_prueba.jpg'

#ruta_imagen_prueba = '/content/Common_rust_2_prueba.jpg'

#ruta_imagen_prueba = '/content/Health_2_prueba.jpg'



# Escribe aquí los nombres EXACTOS de tus 2 enfermedades y la calse saludable en el mismo orden
# alfabético en el que estaban tus carpetas originales.
nombres_clases = ['Blight', 'Common_Rust', 'Healthy']

# --- 2. PREPROCESAMIENTO DE LA IMAGEN ---

print("Procesando la imagen...")
# Cargamos la imagen y la forzamos al tamaño que exige MobileNetV2 (224x224)
img = image.load_img(ruta_imagen_prueba, target_size=(224, 224))

# Convertimos la imagen a un arreglo de números (píxeles)
img_array = image.img_to_array(img)

# El modelo espera recibir "lotes" (batches) de imágenes, no una sola.
# Así que le agregamos una dimensión extra para simular un lote de 1 imagen.
img_array = np.expand_dims(img_array, axis=0)

# --- 3. PREDICCIÓN ---

print("Consultando al modelo...")
# modelo_final ya debe estar cargado en la memoria gracias al Bloque 6
predicciones = modelo_final.predict(img_array)

# predicciones nos da 4 porcentajes. Buscamos cuál es el más alto.
indice_ganador = np.argmax(predicciones[0])
porcentaje_confianza = np.max(predicciones[0]) * 100
clase_predicha = nombres_clases[indice_ganador]

# --- 4. MOSTRAR RESULTADOS ---

print("\n" + "="*40)
print(f" DIAGNÓSTICO DEL MODELO")
print("="*40)
print(f" Clasificación: {clase_predicha}")
print(f" Nivel de Confianza: {porcentaje_confianza:.2f}%")
print("="*40 + "\n")

# Mostramos la imagen en pantalla con su diagnóstico
plt.imshow(img)
plt.axis('off')
plt.title(f"{clase_predicha} ({porcentaje_confianza:.1f}%)", fontsize=14, fontweight='bold', color='green' if porcentaje_confianza > 80 else 'red')
plt.show()